version: '3.9'

services:
  app:
    container_name: store_microservice
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - store_postgres_db
    env_file:
      - .env.stage.docker

  store_postgres_db:
    image: postgres:latest
    restart: always
    ports:
      - "9902:5432"
    env_file:
      - .env.stage.docker
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8802:8080

volumes:
  pg_data:
