services:
  store-app:
    container_name: store_microservice
    build:
      context: .
      target: dev
    ports:
      - "5002:5002"
    depends_on:
      - store_postgres_db
    env_file:
      - .env.stage.docker

  store_postgres_db:
    container_name: postgres-store_db
    image: postgres:latest
    ports:
      - "9902:5432"
    env_file:
      - .env.stage.docker
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    container_name: adminer-store_db
    image: adminer
    ports:
      - 8802:8080

volumes:
  pg_data:
